- name: Install apache2
  apt: name=apache2 state=present

- name: Ensure apache2 is running
  service: name=apache2 state=started

- name: Enable mod_rewrite
  command: a2enmod rewrite

- name: Disable the default apache2 sites
  shell: a2dissite {{ item }}
  notify: restart apache
  with_items:
    - 000-default.conf
    - default-ssl.conf
  when: vagrant

- name: Install prestashop vhost conf file
  sudo: yes
  template: src=prestashop_vhost.conf.j2 dest=/etc/apache2/sites-available/prestashop.conf
  notify: restart apache

- name: Enable Custom Default Sites
  shell: a2ensite {{ item }}
  notify: restart apache
  with_items:
    - prestashop.conf

- name: Change default apache user
  shell: sed -i 's/www-data/vagrant/' /etc/apache2/envvars
  when: vagrant
  notify: restart apache
