- name: Install mysql
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Create prestashop db
  mysql_db: name={{ dbname }} state=present

- name: Create prestashop db user
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv={{ dbname }}.*:ALL

- name: ensure mysql is running
  service: name=mysql state=started
