- name: set locale to {{ locale }}
  action: command /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
  sudo: yes

- name: apt-get update
  command: apt-get update

- name: Install common utilities.
  apt: name={{ item }} state=present
  with_items:
    - curl
    - wget
    - unzip

# For deployments only.
- name: Create user.
  sudo: yes
  action: user home=/home/{{ user_name }} name={{ user_name }} state=present
  when: not vagrant

- name: Create the project directory.
  sudo: yes
  action: file state=directory path={{ project_directory }}
  when: not vagrant
